how to synthesise EAR JWTs
CCC-Attestation/attested-tls-poc pull request #22
Opened 2023-02-24 14:24 UTC by thomas-fossati

2023-03-13 15:10 UTC, paulhowardarm requested changes
Worked like a charm, thank you! Requesting one tiny change, just because one of the shell commands didn't work for me when I pasted it verbatim.

2023-03-13 15:10 UTC, paulhowardarm commented on play-by-ear.md
> +git clone github.com/veraison/ear
I don't think this works exactly as written without the explicit `https://` on the front of the GitHub URL, at least it didn't for me, but possibly it depends on what shell you're using.

2023-03-13 16:28 UTC, thomas-fossati commented on play-by-ear.md
> +git clone github.com/veraison/ear
```suggestion
git clone https://github.com/veraison/ear
```

2023-03-13 16:30 UTC, thomas-fossati commented on play-by-ear.md
> +git clone github.com/veraison/ear
Thanks for spotting this!

2023-03-13 23:23 UTC, thomas-fossati commented on play-by-ear.md
> +git clone github.com/veraison/ear
Fixed in [a2ad0fd](https://github.com/CCC-Attestation/attested-tls-poc/pull/22/commits/a2ad0fda4ae59862a385aef644da74649a52ce73)

2023-03-14 08:09 UTC, paulhowardarm approved these changes
LGTM - thanks for the tweaks

2023-03-14 09:28 UTC, merged